/* DON'T EDIT THIS FILE. This is generated by 'scripts/lib/update-lib-configs-recommended.ts' */

export = {
  plugins: ['cnp'],
  rules: {
    'cnp/declaration-array-type': 'error',
    'cnp/no-console': 'error',
    'cnp/only-import-export': 'error',
  },
};
